"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CssClasses = /** @class */ (function () {
    function CssClasses() {
        this.root = 'ka';
        this.cell = 'ka-cell';
        this.cellEditor = 'ka-cell-editor';
        this.cellText = 'ka-cell-text';
        this.groupCell = 'ka-group-cell';
        this.detailsRow = 'ka-tr ka-details-row';
        this.groupRow = 'ka-tr ka-group-row';
        this.kaCellEditorValidationError = 'ka-cell-editor-validation-error';
        this.row = 'ka-tr ka-row';
        this.rowSelected = 'ka-row-selected';
        this.tableWrapper = 'ka-table-wrapper';
        this.table = 'ka-table';
        this.tbody = 'ka-tbody';
        this.thead = 'ka-thead';
        this.theadBackground = 'ka-thead-background';
        this.theadCell = 'ka-thead-cell';
        this.theadCellContent = 'ka-thead-cell-content';
        this.theadCellContentWrapper = 'ka-thead-cell-content-wrapper';
        this.theadCellResize = 'ka-thead-cell-resize';
        this.theadCellWrapper = 'ka-thead-cell-wrapper';
        this.theadRow = 'ka-tr ka-thead-row';
        this.draggedRow = 'ka-dragged-row';
        this.dragOverRow = 'ka-drag-over-row';
        this.draggedColumn = 'ka-dragged-column';
        this.dragOverColumn = 'ka-drag-over-column';
        this.paging = 'ka-paging';
        this.pagingPages = 'ka-paging-pages';
        this.pagingPageIndex = 'ka-paging-page-index';
        this.iconClose = 'ka-icon ka-icon-close';
        this.iconGroupArrowCollapsed = 'ka-icon ka-icon-group-arrow ka-icon-group-arrow-collapsed';
        this.iconGroupArrowExpanded = 'ka-icon ka-icon-group-arrow ka-icon-group-arrow-expanded';
        this.iconSortArrowDown = 'ka-icon ka-icon-sort ka-icon-sort-arrow-down';
        this.iconSortArrowUp = 'ka-icon ka-icon-sort ka-icon-sort-arrow-up';
        this.checkbox = 'ka-input';
        this.dateInput = 'ka-input';
        this.numberInput = 'ka-input';
        this.textInput = 'ka-input';
    }
    return CssClasses;
}());
exports.CssClasses = CssClasses;
